apiVersion: v1
kind: Service
metadata:
        name: feed-service
spec:
        type: ClusterIP
        ports:
                - protocol: TCP
                  name: http-svc
                  port: 3000
        selector:
                app: feed-server
