apiVersion: v1
kind: Service
metadata:
        name: auth-service
spec:
        type: ClusterIP
        ports:
                - protocol: TCP
                  name: http-svc
                  port: 8037
        selector:
                app: server
